id: P006739
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15472
  title: འབྲུག་གི་ཁྲིམས་གཞུང་། སྒོ་ནོར་ཁྲིམས་ལུགས།
  author: ''
  volumes:
    bf5f540de592412c90840550c6420dda:
      image_group_id: I1KG15481
      title: ''
      volume_number: 1
      total_pages: 100
      base_file: v001.txt
